version: '3.8'

services:
  openhab-fusion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openhab-fusion
    ports:
      - "5050:80"
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped

networks:
  default:
    driver: bridge 